// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: migaloo/feeburn/proposals.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateTxFeeBurnPercentProposal struct {
	Title            string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TxFeeBurnPercent string `protobuf:"bytes,3,opt,name=tx_fee_burn_percent,json=txFeeBurnPercent,proto3" json:"tx_fee_burn_percent,omitempty" yaml:"tx_fee_burn_percent"`
}

func (m *MsgUpdateTxFeeBurnPercentProposal) Reset()         { *m = MsgUpdateTxFeeBurnPercentProposal{} }
func (m *MsgUpdateTxFeeBurnPercentProposal) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateTxFeeBurnPercentProposal) ProtoMessage()    {}
func (*MsgUpdateTxFeeBurnPercentProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a54c48fcb9c6a, []int{0}
}
func (m *MsgUpdateTxFeeBurnPercentProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateTxFeeBurnPercentProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateTxFeeBurnPercentProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateTxFeeBurnPercentProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateTxFeeBurnPercentProposal.Merge(m, src)
}
func (m *MsgUpdateTxFeeBurnPercentProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateTxFeeBurnPercentProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateTxFeeBurnPercentProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateTxFeeBurnPercentProposal proto.InternalMessageInfo

func (m *MsgUpdateTxFeeBurnPercentProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUpdateTxFeeBurnPercentProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgUpdateTxFeeBurnPercentProposal) GetTxFeeBurnPercent() string {
	if m != nil {
		return m.TxFeeBurnPercent
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgUpdateTxFeeBurnPercentProposal)(nil), "migaloo.feeburn.MsgUpdateTxFeeBurnPercentProposal")
}

func init() { proto.RegisterFile("migaloo/feeburn/proposals.proto", fileDescriptor_a97a54c48fcb9c6a) }

var fileDescriptor_a97a54c48fcb9c6a = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0xdf, 0x87, 0x82, 0x71, 0xa1, 0xc4, 0x2e, 0x4a, 0x91, 0x69, 0xed, 0xca, 0x4d,
	0x32, 0x8b, 0xee, 0x5c, 0x06, 0x75, 0x57, 0x08, 0x45, 0x29, 0xb8, 0x09, 0x93, 0xf4, 0x26, 0x19,
	0x98, 0x64, 0x86, 0xc9, 0x8d, 0xa4, 0x6f, 0xe1, 0x73, 0xf8, 0x24, 0x2e, 0xbb, 0x74, 0x25, 0x92,
	0xbc, 0x81, 0x4f, 0x20, 0xf9, 0x83, 0x88, 0xba, 0xbb, 0xf7, 0x9e, 0x1f, 0xe7, 0x5c, 0x8e, 0x35,
	0xcb, 0x44, 0xc2, 0xa5, 0x52, 0x2c, 0x06, 0x08, 0x4b, 0x93, 0x33, 0x6d, 0x94, 0x56, 0x05, 0x97,
	0x85, 0xab, 0x8d, 0x42, 0x65, 0x9f, 0x0c, 0x80, 0x3b, 0x00, 0xd3, 0x71, 0xa2, 0x12, 0xd5, 0x69,
	0xac, 0x9d, 0x7a, 0x6c, 0x7a, 0xfe, 0xcb, 0x87, 0x1b, 0x9e, 0x0d, 0x26, 0x8b, 0x67, 0x62, 0x5d,
	0xac, 0x8a, 0xe4, 0x5e, 0x6f, 0x39, 0xc2, 0x5d, 0x75, 0x0b, 0xe0, 0x95, 0x26, 0xf7, 0xc1, 0x44,
	0x90, 0xa3, 0x3f, 0x24, 0xda, 0x63, 0xeb, 0x00, 0x05, 0x4a, 0x98, 0x90, 0x39, 0xb9, 0x3c, 0x5a,
	0xf7, 0x8b, 0x3d, 0xb7, 0x8e, 0xb7, 0x50, 0x44, 0x46, 0x68, 0x14, 0x2a, 0x9f, 0xfc, 0xeb, 0xb4,
	0xef, 0x27, 0x7b, 0x65, 0x9d, 0x61, 0x15, 0xc4, 0x00, 0x41, 0x9b, 0x1c, 0xe8, 0xde, 0x76, 0xf2,
	0xbf, 0x25, 0x3d, 0xfa, 0xf1, 0x36, 0x9b, 0xee, 0x78, 0x26, 0xaf, 0x16, 0x7f, 0x40, 0x8b, 0xf5,
	0x29, 0xfe, 0x78, 0xc7, 0x0b, 0x5e, 0x6a, 0x4a, 0xf6, 0x35, 0x25, 0xef, 0x35, 0x25, 0x4f, 0x0d,
	0x1d, 0xed, 0x1b, 0x3a, 0x7a, 0x6d, 0xe8, 0xe8, 0xe1, 0x26, 0x11, 0x98, 0x96, 0xa1, 0x1b, 0xa9,
	0x8c, 0x6d, 0x52, 0x81, 0xe0, 0x6c, 0x52, 0x2e, 0xc1, 0xb9, 0x86, 0x58, 0x38, 0xbe, 0xe4, 0x18,
	0x2b, 0x93, 0xb1, 0xa1, 0x09, 0x27, 0x4a, 0xb9, 0xc8, 0xd9, 0xe3, 0x92, 0x55, 0x5f, 0xa5, 0xe0,
	0x4e, 0x43, 0x11, 0x1e, 0x76, 0xa5, 0x2c, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa8, 0x3e,
	0x96, 0x7c, 0x01, 0x00, 0x00,
}

func (m *MsgUpdateTxFeeBurnPercentProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateTxFeeBurnPercentProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateTxFeeBurnPercentProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxFeeBurnPercent) > 0 {
		i -= len(m.TxFeeBurnPercent)
		copy(dAtA[i:], m.TxFeeBurnPercent)
		i = encodeVarintProposals(dAtA, i, uint64(len(m.TxFeeBurnPercent)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposals(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposals(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposals(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposals(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateTxFeeBurnPercentProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposals(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposals(uint64(l))
	}
	l = len(m.TxFeeBurnPercent)
	if l > 0 {
		n += 1 + l + sovProposals(uint64(l))
	}
	return n
}

func sovProposals(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposals(x uint64) (n int) {
	return sovProposals(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateTxFeeBurnPercentProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposals
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateTxFeeBurnPercentProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateTxFeeBurnPercentProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFeeBurnPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxFeeBurnPercent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProposals(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposals
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposals(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposals
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposals
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposals
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposals
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposals
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposals
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposals        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposals          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposals = fmt.Errorf("proto: unexpected end of group")
)
