name: Interchain Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build_push_image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/white-whale-defi-platform/migaloo-chain-ictest:latest
  test-start-cosmos-chain:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-start-cosmos
        env:
          BRANCH_CI: 'latest'
  test-ibc-transfer:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-ibc
        env:
          BRANCH_CI: 'latest'
